### ISSUE TITLE
Any Chance for New Update?

### ISSUE THREAD

**Issue by soeryobadja** [Asteerix/Hackintosh-Lenovo-Thinkpad-T470s#2]
Hi,

Great work with the EFI here. 
Any chance you will make an update to the project? 
I use your EFI and things work great, except:
1. TB not working - not sure 6240 Alpine Ridge is natively supported though. 
2. USB-C port not working unless you plug USB-C device from boot. 
3. Left-side USB-A port (next to charger port) cannot work in SS USB mode, only 480Mbps HS USB speed. 
4. Sleep does not work properly - DarkWake from normal sleep due to XDCI.

Great work though, hoping that this project is still continuing. 

Thanks.

**Comment by Asteerix** [comment]
Hello @soeryobadja,

Thank you very much, on my side I didn’t have any problem with the EFI. 
I already perfected my work on this project several times, but locally on my external drive before I finally published it on Github so that others can benefit from it.
Of course, for every modification, I would attach them on this Github repository.

I never checked the USB-C port, but I would consider testing it and adding the functionality to use it.
The USB-A port on my PC works very well for me, as well as the sleep mode.

I would check everything by doing many tests and patch the problems ;).

Thanks for your feedback ;)

**Comment by Asteerix** [comment]
Hello @soeryobadja,

Thank you very much, on my side I didn’t have any problem with the EFI.
I already perfected my work on this project several times, but locally on my external drive before I finally published it on Github so that others can benefit from it.
Of course, for every modification, I would attach them on this Github repository.

I never checked the USB-C port, but I would consider testing it and adding the functionality to use it.
The USB-A port on my PC works very well for me, as well as the sleep mode.

I would check everything by doing many tests and patch the problems ;).

Thanks for your feedback ;)
